# Generated by Django 3.1.4 on 2020-12-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201208_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_no',
            field=models.IntegerField(null=True),
        ),
    ]
