# Generated by Django 3.1.4 on 2020-12-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_episode_episode_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='thambnail',
            new_name='thumbnail',
        ),
    ]
